apiVersion: batch/v1
kind: CronJob
metadata:
  name: usb-check
  namespace: default
spec:
  schedule: "*/5 * * * *"  # Toutes les 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: usb-check
        spec:
          nodeSelector:
            kubernetes.io/hostname: vm3-2f48f538
          containers:
          - name: usb-check
            image: uncledhafer/usb-check:latest
            volumeMounts:
            - name: usb-bus
              mountPath: /dev/bus/usb
            - name: sysfs
              mountPath: /sys
            securityContext:
              privileged: true
          restartPolicy: Never
          volumes:
          - name: usb-bus
            hostPath:
              path: /dev/bus/usb
              type: Directory
          - name: sysfs
            hostPath:
              path: /sys
              type: Directory

