apiVersion: batch/v1
kind: Job
metadata:
  name: usb-check
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm3-2f48f538  # ou vm4-448b6698 selon où tu veux tester
      containers:
      - name: usb-check
        image: uncledhafer/usb-check:latest
        volumeMounts:
        - name: usb-bus
          mountPath: /dev/bus/usb
        - name: sysfs
          mountPath: /sys
        securityContext:
          privileged: true
      restartPolicy: Never
      volumes:
      - name: usb-bus
        hostPath:
          path: /dev/bus/usb
      - name: sysfs
        hostPath:
          path: /sys
  backoffLimit: 0

